### ISSUE TITLE
Design Document - Level 1 Data Flow Diagram

### ISSUE THREAD

**Issue by sbirvin1s** [JapanAintSunCamp/CS4500-PHASE3#20]
- [x] Determine the program to use to create a Data Flow Diagram
- [x] Create Level 1 Data Flow Diagram

Potential programs/ DFD solutions
- [Mermaid ](https://mermaid.live/edit#pako:eNpVjsFqw0AMRH9F6NRC_AM-FBq7zSWQQnOqnYOwZe-S7GqR14Rg-9-7TlpodZJm3gyasJGWMcfuItfGkEY4lrWHNK9VYdQO0dFwgix7mXccwYnn2wzbp53AYCQE6_vnB79dISim_YoxRGP9eXlYxT1_8DxDWe0pRAmnv87xKjO8VfbDpPr_jlFOqfeqo7yjrCGFgvSO4AYdqyPbpvenVakxGnZcY57WlvRcY-2XxNEY5fPmG8yjjrxBlbE3mAovQ7rG0FLk0lKv5H6RQP5LxP1AyzeJDl_b)
- [Miro](https://miro.com/index/)
- [Draw.io](https://app.diagrams.net/)

**Comment by vkkostin** [comment]
[DataFlowDiagram.pdf](https://github.com/user-attachments/files/17922289/DataFlowDiagram.pdf)
